version: '3'
services:
  laravel:
    build:
      context: ./docker
      dockerfile: laravel.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=hairpin
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Shanghai
    ports:
      - "9000:9000"


  database:
    image: mysql:8
    restart: always
    volumes:
      - hairpin_mysql_data:/var/lib/mysql:rw
      - hairpin_mysql_log:/var/log/mysql:rw
      - hairpin_mysql_config:/etc/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 33306:3306

  redis:
    build:
      context: ./docker
      dockerfile: redis.dockerfile
    ports:
      - 63799:6379

  proxy:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/var/www/:cached
    # 开发环境需取消端口调试开放
    ports:
      - 80:80
    links:
      - laravel
    working_dir: "/var/www"
    restart: "no"

volumes:
  hairpin_mysql_data:
  hairpin_mysql_log:
  hairpin_mysql_config:

